### ISSUE TITLE
 更新一下 ios    阿里推送的 sdk 吧 ，更新后 IOS13 的deviceToken问题处理了

### ISSUE THREAD

**Issue by a188658587** [wonday/react-native-aliyun-push#112]

**Comment by a188658587** [comment]
已经更新了

**Comment by IT-LiuSir** [comment]
目前我集成最新版的1.0.21，为何提示“Register deviceToken failed, error: Error Domain=vip_error_domain Code=5003 "(null)" UserInfo={Error reason=VIP请求失败，接口调用错误”，不清楚什么原因造成，请问如何解决
