### ISSUE TITLE
集成代码中提示HuaWeiRegister无效

### ISSUE THREAD

**Issue by bigkrys** [wonday/react-native-aliyun-push#116]
Task :app:compileDebugJavaWithJavac FAILED
D:\egame_android\android\app\src\main\java\com\egame_android\MainApplication.java:38: 错误: 找不到符号
import com.alibaba.sdk.android.push.register.HuaWeiRegister;
                                            ^
  符号:   类 HuaWeiRegister
  位置: 程序包 com.alibaba.sdk.android.push.register
D:\egame_android\android\app\src\main\java\com\egame_android\MainApplication.java:128: 错误: 找不到符号
      HuaWeiRegister.register(applicationContext);
      ^
  符号:   变量 HuaWeiRegister
  位置: 类 MainApplication
2 个错误

**Comment by shenyuanqing** [comment]
@bigkrys 新版华为的注册方法变了吧，
import com.alibaba.sdk.android.push.huawei.HuaWeiRegister;
HuaWeiRegister.register(Application application)

**Comment by zhonggithub** [comment]
![image](https://user-images.githubusercontent.com/17545551/68108713-8dd51100-ff23-11e9-84bc-986fa0a0b5e4.png)
这个是怎么解决的

**Comment by ppdbxdawj** [comment]
> ![image](https://user-images.githubusercontent.com/17545551/68108713-8dd51100-ff23-11e9-84bc-986fa0a0b5e4.png)
> 这个是怎么解决的

可以尝试在android->app->src->main->res->values->styles.xml中添加如下代码
`<style name="upsdkDlDialog" parent="@android:style/Theme.Holo.Light">
     <item name="android:windowBackground">@android:color/transparent</item>
     <item name="android:windowNoTitle">true</item>
     <item name="android:windowIsTranslucent">true</item>
 </style>`
希望对您有所帮助

**Comment by ppdbxdawj** [comment]
> ![image](https://user-images.githubusercontent.com/17545551/68108713-8dd51100-ff23-11e9-84bc-986fa0a0b5e4.png)
> 这个是怎么解决的

可以尝试在android->app->src->main->res->values->styles.xml中添加如下代码
 ```
<style name="upsdkDlDialog" parent="@android:style/Theme.Holo.Light"> 
   <item name="android:windowBackground">@android:color/transparent</item>
   <item name="android:windowNoTitle">true</item>
   <item name="android:windowIsTranslucent">true</item>
</style>
 ```
希望对您有所帮助

**Comment by zhonggithub** [comment]
> > ![image](https://user-images.githubusercontent.com/17545551/68108713-8dd51100-ff23-11e9-84bc-986fa0a0b5e4.png)
> > 这个是怎么解决的
> 
> 可以尝试在android->app->src->main->res->values->styles.xml中添加如下代码
> 
> ```
> <style name="upsdkDlDialog" parent="@android:style/Theme.Holo.Light"> 
>   <item name="android:windowBackground">@android:color/transparent</item>
>   <item name="android:windowNoTitle">true</item>
>   <item name="android:windowIsTranslucent">true</item>
> </style>
> ```
> 
> 希望对您有所帮助

感谢，已解决

**Comment by ppdbxdawj** [comment]
> Task :app:compileDebugJavaWithJavac FAILED
> D:\egame_android\android\app\src\main\java\com\egame_android\MainApplication.java:38: 错误: 找不到符号
> import com.alibaba.sdk.android.push.register.HuaWeiRegister;
> ^
> 符号: 类 HuaWeiRegister
> 位置: 程序包 com.alibaba.sdk.android.push.register
> D:\egame_android\android\app\src\main\java\com\egame_android\MainApplication.java:128: 错误: 找不到符号
> HuaWeiRegister.register(applicationContext);
> ^
> 符号: 变量 HuaWeiRegister
> 位置: 类 MainApplication
> 2 个错误

请问这个找到解决方法了吗？可以正确集成到最后的

**Comment by bigkrys** [comment]
> > Task :app:compileDebugJavaWithJavac FAILED
> > D:\egame_android\android\app\src\main\java\com\egame_android\MainApplication.java:38: 错误: 找不到符号
> > import com.alibaba.sdk.android.push.register.HuaWeiRegister;
> > ^
> > 符号: 类 HuaWeiRegister
> > 位置: 程序包 com.alibaba.sdk.android.push.register
> > D:\egame_android\android\app\src\main\java\com\egame_android\MainApplication.java:128: 错误: 找不到符号
> > HuaWeiRegister.register(applicationContext);
> > ^
> > 符号: 变量 HuaWeiRegister
> > 位置: 类 MainApplication
> > 2 个错误
> 
> 请问这个找到解决方法了吗？可以正确集成到最后的

我更新了版本后，然后用android studio sync一下就好了

**Comment by wonday** [comment]
@ppdbxdawj  import变了，请使用如下：
```
import com.alibaba.sdk.android.push.huawei.HuaWeiRegister;
```

**Comment by ppdbxdawj** [comment]
> @ppdbxdawj import变了，请使用如下：
> 
> ```
> import com.alibaba.sdk.android.push.huawei.HuaWeiRegister;
> ```

您好，按照您的方法更改之后，若仍用`HuaWeiRegister.register(applicationContext);`则会报错如下
![image](https://user-images.githubusercontent.com/31980330/68185828-7d816c80-ffdd-11e9-9dbb-150ce62ac1bc.png)
是否仍需要进行其他的修改
谢谢

**Comment by wonday** [comment]
@ppdbxdawj 
改为如下：
```
HuaWeiRegister.register(this);
```
