### ISSUE TITLE
Android: The logic of judging MIUI is not correct, this will cause setApplicationIconBadgeNumber has no effect

### ISSUE THREAD

**Issue by HawkQing** [wonday/react-native-aliyun-push#117]
The logic of judging MIUI is not correct, this will cause setApplicationIconBadgeNumber has no effect.
I changed the logic as follows:
public static boolean isMIUI(Context context) {
        if(hasChecked)
        {
            return isMIUI;
        }
        try {
            SystemProperty sp = new SystemProperty(context);
            String ret1 = "";
            String ret2 = "";
            String ret3 = "";
            ret1 = sp.getOrThrow(KEY_MIUI_VERSION_CODE);
            ret2 = sp.getOrThrow(KEY_MIUI_VERSION_NAME);
            ret3 = sp.getOrThrow(KEY_MIUI_INTERNAL_STORAGE);
            if ( (ret1 != null && ret1.compareToIgnoreCase("") != 0) ||
                    (ret2 != null && ret2.compareToIgnoreCase("") != 0) ||
                    (ret3 != null && ret3.compareToIgnoreCase("") != 0)) {
                hasChecked = true;
                isMIUI = true;
            }
        } catch (Exception e)
        {
            e.printStackTrace();
            return false;
        }
        
        return isMIUI;
    }.
Hope to help people who encounter the same issue.

**Comment by wonday** [comment]
Thank you, I have added it to master.
