### ISSUE TITLE
Could not find auto-value-annotations.jar

### ISSUE THREAD

**Issue by bigkrys** [wonday/react-native-aliyun-push#118]
![image](https://user-images.githubusercontent.com/17899020/68281197-15508a80-00b2-11ea-9e68-9c2c1a67a83c.png)

**Comment by zhonggithub** [comment]
same issue

**Comment by zhonggithub** [comment]
兄弟有找到解决办法吗

**Comment by zhonggithub** [comment]
如图 修改 聚可以了
![image](https://user-images.githubusercontent.com/17545551/68557169-fcf4bd00-046f-11ea-967c-2ca558d32974.png)

**Comment by bigkrys** [comment]
> 如图 修改 就可以了
> ![image](https://user-images.githubusercontent.com/17545551/68557169-fcf4bd00-046f-11ea-967c-2ca558d32974.png)

感谢！
