### ISSUE TITLE
用阿里云测试发送推送，关闭APP的时候收不到通知，一开启App就会收到发出的通知

### ISSUE THREAD

**Issue by 904492381** [wonday/react-native-aliyun-push#120]
这是为什么？小米手机，杀死APP后，发送推送，收不到，一打开APP就立马收到通知栏的通知
@wonday

**Comment by 904492381** [comment]
我发现华为也是 是哪里出了问题吗

**Comment by 904492381** [comment]
华为可以了

**Comment by wonday** [comment]
应该是第三方通道没配置好。
打开后使用了阿里云自己的通道。

**Comment by 904492381** [comment]
> 应该是第三方通道没配置好。
> 打开后使用了阿里云自己的通道。

如果不使用小米第三方通道，关闭APP时会收到通知吗  我应该是配置好了 检查了好几遍

**Comment by 904492381** [comment]
@wonday  请问下 如果没配置小米第三方通道 杀死APP后会接收到通知吗

**Comment by wonday** [comment]
不配置第三方通道， 杀死app, 是不会接到通知的。
第三方通道就是为了确保app死后可以收到通知。

**Comment by 54sword** [comment]
@904492381 请问解决了吗？使用RN 0.61.5，也遇到了相同的问题。
之前在RN 0.59版本没问题，使用新版本后配置没调成功，第三方通道也配置了，不知道怎么回事。

![截屏2020-02-09下午5 50 53](https://user-images.githubusercontent.com/888115/74100011-d9233f00-4b64-11ea-8f44-5bf31748127d.png)

@wonday 
app关闭后收不到通知，打开后可以收到。

**Comment by lql25** [comment]
我试过1.0.15是正常的，辅助通道可以收到，升级版本为1.0.21，辅助通道就收不到了，求解决
