### ISSUE TITLE
framework not found UTDID

### ISSUE THREAD

**Issue by lixiaozhangme** [wonday/react-native-aliyun-push#13]
@wonday ;
第三方的模块我按照你的方法拖拽，并打勾了，但是包这个错误‘ramework not found UTDID’
![image](https://user-images.githubusercontent.com/19645470/34038741-59ad9cb4-e1c8-11e7-9b63-88d243beff65.png)
![image](https://user-images.githubusercontent.com/19645470/34038785-765f3db8-e1c8-11e7-9a13-c6954a4d29a2.png)

**Comment by yewenxiang23** [comment]
+1我也碰到这个问题

**Comment by yewenxiang23** [comment]
@lixiaozhangme 请问你解决了吗，难道和没有添加开发者证书有关系？我使用的是自己的appID.

**Comment by wonday** [comment]
也许是你没有把这个库添加到link中，
确保targets app的BuildPhase的Link Binary With Libraries包含

AlicloudUtils.framework
CloudPushSDK.framework
UTDID.framework
UTMini.framework

**Comment by coderafei** [comment]
+1 最新版也报UTDID错误，试了好长时间

**Comment by wonday** [comment]
截图targets app的BuildPhase的Link Binary With Libraries，
我看看里面是否包含相关库

**Comment by ZevenFang** [comment]
我的也遇到了类似的错误
![image](https://user-images.githubusercontent.com/11134329/36944040-d362a4d4-1fce-11e8-9ae2-0a6dd12a628f.png)
![image](https://user-images.githubusercontent.com/11134329/36944038-bb41529c-1fce-11e8-96c2-2c101b2c64e3.png)

**Comment by ZevenFang** [comment]
解决了，
在 Build Settings -> Framework Search Paths 添加：
```
$(SRCROOT)/../node_modules/react-native-aliyun-push/ios/libs
```
