### ISSUE TITLE
ios接受到消息之后这里会报错卡死，实在看不懂ios，麻烦帮忙看下

### ISSUE THREAD

**Issue by u373649715** [wonday/react-native-aliyun-push#15]
- (void)onMessageReceived:(NSNotification *)notification
{
    DLog(@"onMessageReceived.");
    
    NSMutableDictionary *notificationDict = [notification object];
    
    // 取得通知自定义字段内容
    notificationDict[@"extras"] = [notification userInfo];//这里会报错
    
    // 类型 “notification” or "message"
    notificationDict[@"type"] = ALIYUN_PUSH_TYPE_MESSAGE;//这里会报错
    
    [self sendEventToJs:notificationDict];
    
}
- (void)sendEventToJs:(NSMutableDictionary*)notification
{
    DLog(@"sendEventToJs:");
    
    for (NSString *key in notification) {//这里会报错
        DLog(@"key: %@ value: %@", key, notification[key]);
    }
    
    [self sendEventWithName:@"aliyunPushReceived" body:notification];
}

注释上面三处之后，不报错了，但是推送消息的时候js没有获取到内容，推送通知的时候没有反应

**Comment by wonday** [comment]
报什么错？截个屏给我看看

**Comment by u373649715** [comment]
![Uploading ios消息报错.png…]()
都是这样的报错

**Comment by u373649715** [comment]
![ios](https://user-images.githubusercontent.com/33892406/34804402-70c10454-f6b3-11e7-8487-8ef1833143ac.png)
都是这样的报错

**Comment by wonday** [comment]
代码写错了， 你使用下面的代码替换一下试试？

```
- (void)onMessageReceived:(NSNotification *)notification
{
    DLog(@"onMessageReceived.");
    
    NSMutableDictionary *notificationDict = [NSMutableDictionary dictionary];
    
    CCPSysMessage *message = [notification object];
    
    notificationDict[@"title"] = [[NSString alloc] initWithData:message.title encoding:NSUTF8StringEncoding];
    notificationDict[@"body"] = [[NSString alloc] initWithData:message.body encoding:NSUTF8StringEncoding];
    // 取得通知自定义字段内容
    if (notification.userInfo) {
        notificationDict[@"extras"] = notification.userInfo;
    } else {
        notificationDict[@"extras"] = @{};
    }
    
    
    // 类型 “notification” or "message"
    notificationDict[@"type"] = ALIYUN_PUSH_TYPE_MESSAGE;
    
    [self sendEventToJs:notificationDict];
    
}
```
没问题，我正式发布一下。

**Comment by u373649715** [comment]
可以了可以了，你这个还是蛮好用的，阿里官方文档各种报错

**Comment by wonday** [comment]
OK, 顺便更新了一下SDK, 我发布个新版本。

**Comment by wonday** [comment]
已发布1.0.6
