### ISSUE TITLE
ios老提示错误

### ISSUE THREAD

**Issue by benaheng** [wonday/react-native-aliyun-push#2]
按照说明一步一步操作的，但是最后真机调试的时候老是报错，这是什么原因？

`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_AliyunPushManager", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by wonday** [comment]
应该是react-native link react-native-aliyun-push没有成功。

请确认一下：

1. react-native-aliyun-push是否添加到了工程中（左边工程树中，应该在Libraries下）
2. 项目设置的General tab最下面Linked Framework and Libraries中应该有libRTCAliyunPush.a
看上去应该是第二个没有成功， 如果没有请手工添加一下。

**Comment by benaheng** [comment]
嗯，果然是第二个原因导致的，多谢！！
