### ISSUE TITLE
ios正常，android一有消息推送到达，就闪退？

### ISSUE THREAD

**Issue by BooYeu** [wonday/react-native-aliyun-push#21]
![9dc9c17de4bb315fb8528ac7299672a4](https://user-images.githubusercontent.com/16587763/38021240-30dc1702-3231-11e8-8960-582f77907c07.png)

**Comment by wonday** [comment]
能打开log, 看看什么地方死掉了吗？

**Comment by BooYeu** [comment]
不好意思 前面我忘记bundle了，所以删掉了handleAliyunPushMessage里代码还是闪退，是我handleAliyunPushMessage代码写错了。非常感谢及时的回复！！！
