### ISSUE TITLE
ios关闭app进程，写在handleAliyunPushMessage里的函数不执行？

### ISSUE THREAD

**Issue by BooYeu** [wonday/react-native-aliyun-push#22]
有没有什么替代方法？

**Comment by wonday** [comment]
是不是和 #23  有关？ 我已经修正#23 并发新版本。

**Comment by BooYeu** [comment]
添加了判断在前台才可以发送Event，但如果不在前台，event能自动延迟发送吗？

**Comment by wonday** [comment]
什么样的延迟机制合适呢？

**Comment by BooYeu** [comment]
当用户打开app时 依次执行新到通知的 handleAliyunPushMessage？这样能实现吗？

**Comment by BooYeu** [comment]
安卓好像没影响，在后台也能在收到的同时执行，但ios不行，好像就直接跳过handleAliyunPushMessage了

**Comment by wonday** [comment]
这样不知道会堆积多少， 建议App启动后自己从后台拉取一下用户消息。

**Comment by BooYeu** [comment]
好的也只能这样了，谢谢～～
