### ISSUE TITLE
app退出后，收到通知，点击通知后app闪退

### ISSUE THREAD

**Issue by wuzhenheng** [wonday/react-native-aliyun-push#23]
iOS:
app退出后，收到通知，点击通知后app闪退
app未退出，收到通知，点击通知正常。

**Comment by wuzhenheng** [comment]
修改后可用。

- (void)sendEventToJs:(NSMutableDictionary*)notification
{
    DLog(@"sendEventToJs:");
    
    for (NSString *key in notification) {
        DLog(@"key: %@ value: %@", key, notification[key]);
    }
    //是否在前台判断，在前台才可以发送Event
    if([UIApplication sharedApplication].applicationState == UIApplicationStateActive) {
        [self sendEventWithName:@"aliyunPushReceived" body:notification];
    }
    
}

**Comment by wonday** [comment]
谢谢， 我合并了你的修改并发布了新版本。
