### ISSUE TITLE
IOS端缺少角标同步API

### ISSUE THREAD

**Issue by Covenanter** [wonday/react-native-aliyun-push#27]
IOS端缺少角标同步API~RT

**Comment by Covenanter** [comment]
@wonday ios你没有测试吧？

**Comment by wonday** [comment]
目前我的实现方法和你的想法不一样。
我的方法是：
1. 自己服务器端维护用户通知数量
2. 给用户通知时把这个数量带过去，
3. app端这个模块收到通知时把角标设置上去。

目前android和ios都可正常使用。

我看阿里增加了一些接口，就是你想要用的。
他的流程是：
1. 推送时不用提供角标数量，设置自增标记。
2. iOS端sdk收到后会设置到角标，同时要求用户把app端角标同步到阿里云服务器供下一次自增用。

阿里云的方案的好处时不用我们app服务端记录角标数， 缺点是没有android对应设置。
你的修改方案可能还不彻底，可能会和我的方案有干扰，我看看能否兼容考虑一下，下个版本修改。

**Comment by Covenanter** [comment]
@wonday 我这边的需求是，接受到消息在icon显示角标数量，点击app进去后，清空所有的数量。在android上是没问题的，由于我使用openAPI推送ios设置自增长角标，角标是由阿里中进行维护。所以我需要置0数量，需要使用到同步的方法。

我在PR中只是在IOS中加了同步角标的方法。

**Comment by zlipeng** [comment]
@Covenanter 你好，我想问一下，使用openAPI推送ios设置自增长角标这一步，无论我使用node-sdk还是python-sdk都会报Unexpected key 'iOSBadgeAutoIncrement' found in params 这样的错误，想知道你是怎么设置的
