### ISSUE TITLE
进程关闭后，点击推送通知，进入APP，获取不到推送信息

### ISSUE THREAD

**Issue by lzctbyong** [wonday/react-native-aliyun-push#3]
如题

**Comment by wonday** [comment]
如果程序打开中，可以收到通知，可以显示给用户，

如果程序关闭时，应该还不可以点击通知打开app显示推送信息。

可能的做法如下：
1.
推送时候附带一个程序schema url,  类似 weixin://host/share?param1=xxx
你的消息同时也写到url上去。
启动程序后使用Linking取得启动url, 解析消息内容，然后进行显示。

2.
推送时候附带一个程序schema url,  类似 weixin://host/share?id=xxx
你的消息id同时也写到url上去。
启动程序后使用Linking取得启动url, 解析url取得消息ID,然后从你的服务器取得消息内容显示。

3. 
不使用程序schema url, 程序启动后自己从服务器拉去改显示给用户的消息进行显示。
当然要自己控制已读未读之类的。

仅供参考。

**Comment by lzctbyong** [comment]
对于小米的辅助窗口推送，点击通知如果获取信息给RN？

**Comment by lzctbyong** [comment]
` protected void onSysNoticeOpened(String title, String summary, Map<String, String> extMap) {
        Log.d(ReactConstants.TAG, "Receive notification, title: " + title + ", content: " + summary + ", extraMap: " + extMap);
        if (AliyunPushModule.AliyunPushMessageReceiver.instance != null) {
            AliyunPushModule.AliyunPushMessageReceiver.instance.onNotification(context, title, summary, extMap);
            if (ThirdPartMessageActivity.mainClass != null) {
                Intent itent = new Intent();
                itent.setClass(ThirdPartMessageActivity.this, mainClass);
                Bundle bundle = new Bundle();
                startActivity(itent);
                ThirdPartMessageActivity.this.finish();
            }
        }
    }`

这段代码，对于小米辅助窗口，这时候RN还没启动，你 sendEvent("aliyunPushReceived", params); 也收不到事件的吧 @wonday

**Comment by wonday** [comment]
手头没有小米手机，代码写了一些，一直没有好好测试。

首先要在MainApplication.java中

···
  private void initCloudChannel() {
    PushServiceFactory.init(this.getApplicationContext());
    CloudPushService pushService = PushServiceFactory.getCloudPushService();
    pushService.setNotificationSmallIcon(R.mipmap.ic_launcher_s);
    pushService.register(this.getApplicationContext(), "***", "******", new CommonCallback() {
      @Override
      public void onSuccess(String response) {
        FLog.d(ReactConstants.TAG, "init aliyun push cloudchannel success");
      }
      @Override
      public void onFailed(String code, String message) {
        FLog.d(ReactConstants.TAG, "init aliyun push cloudchannel failed. errorCode:" + code + ". errorMsg:" + message);
      }
    });

    // 注册方法会自动判断是否支持小米系统推送，如不支持会跳过注册。
    MiPushRegister.register(this.getApplicationContext(), "******", "******");
    // 注册方法会自动判断是否支持华为系统推送，如不支持会跳过注册。
    HuaWeiRegister.register(this.getApplicationContext());
  }
···

把其中星号的部分换成你申请的账号，然后RN接收路线是一样的。
华为不知道是否也有账号要申请，还没仔细研究...

**Comment by lzctbyong** [comment]
你这个是初始化，我现在问题是，进程关闭下，能收到小米的辅助窗口通知，但是不知道怎么把推送内容给到RN

**Comment by wonday** [comment]
你现在已经能够执行到onSysNoticeOpened了？

**Comment by lzctbyong** [comment]
按照阿里的文档，当辅助窗口通知时，就要执行onSysNoticeOpened

 
阿里文档是这么说的
> AndroidPopupActivity中提供抽象方法onSysNoticeOpened()，实现该方法后可获取到辅助弹窗通知的标题、内容和额外参数，在通知点击时触发，原本的通知回调onNotification()和onNotificationOpened()不适用于辅助弹窗；

**Comment by wonday** [comment]
如果app没启动, 在onSysNoticeOpened， 上面代码可能是发送不过去给RN的。
估计要做更多处理：
1.启动app 
2.把消息内容发给MainActivity
3.MainActivity把消息内容转到RN里面来。

MainActivity是RN控制的， 不知道能否改造成接收消息内容，
手头上没有小米手机，暂时没办法试验...

app启动时可以收到推送的， 这个测试过。

**Comment by lzctbyong** [comment]
普通推送是没问题的，这个我先自己研究下吧

**Comment by gao520sun** [comment]
我的项目搞定了

**Comment by wonday** [comment]
@gao520sun 
搞定什么了？app被kill后点击通知可以打开显示通知？
能说的详细一点吗？

**Comment by gao520sun** [comment]
@wonday 
应用程序被杀死后点击通知可以打开显示通知

在android中写了一个单利，保存通知的值，然后再打开app在去获取。

**Comment by gao520sun** [comment]
protected void onSysNoticeOpened(String title, String summary, Map<String, String> extMap) {
        WritableMap params = Arguments.createMap();

        WritableMap extraWritableMap = Arguments.createMap();
        for (Map.Entry<String, String> entry : extMap.entrySet()) {
            extraWritableMap.putString(entry.getKey(),entry.getValue());
        }
        params.putMap("extras", extraWritableMap);

        params.putString("type", ALIYUN_PUSH_TYPE_NOTIFICATION);
        params.putString("title", title);
        params.putString("summary", summary);


        SaveInstanceMessage.getInstance().setNotificationMessage(params);


        Intent itent=new Intent();
        itent.setClass(ThirdPartMessageActivity.this, MainActivity.class);
        startActivity(itent);

        ThirdPartMessageActivity.this.finish();


    }

**Comment by wonday** [comment]
@gao520sun 
谢谢你的探索👍

**Comment by ma6566966** [comment]
> protected void onSysNoticeOpened(String title, String summary, Map<String, String> extMap) { WritableMap params = Arguments.createMap();
> 
> ```
>     WritableMap extraWritableMap = Arguments.createMap();
>     for (Map.Entry<String, String> entry : extMap.entrySet()) {
>         extraWritableMap.putString(entry.getKey(),entry.getValue());
>     }
>     params.putMap("extras", extraWritableMap);
> 
>     params.putString("type", ALIYUN_PUSH_TYPE_NOTIFICATION);
>     params.putString("title", title);
>     params.putString("summary", summary);
> 
> 
>     SaveInstanceMessage.getInstance().setNotificationMessage(params);
> 
> 
>     Intent itent=new Intent();
>     itent.setClass(ThirdPartMessageActivity.this, MainActivity.class);
>     startActivity(itent);
> 
>     ThirdPartMessageActivity.this.finish();
> 
> 
> }
> ```



> protected void onSysNoticeOpened(String title, String summary, Map<String, String> extMap) { WritableMap params = Arguments.createMap();
> 
> ```
>     WritableMap extraWritableMap = Arguments.createMap();
>     for (Map.Entry<String, String> entry : extMap.entrySet()) {
>         extraWritableMap.putString(entry.getKey(),entry.getValue());
>     }
>     params.putMap("extras", extraWritableMap);
> 
>     params.putString("type", ALIYUN_PUSH_TYPE_NOTIFICATION);
>     params.putString("title", title);
>     params.putString("summary", summary);
> 
> 
>     SaveInstanceMessage.getInstance().setNotificationMessage(params);
> 
> 
>     Intent itent=new Intent();
>     itent.setClass(ThirdPartMessageActivity.this, MainActivity.class);
>     startActivity(itent);
> 
>     ThirdPartMessageActivity.this.finish();
> 
> 
> }
> ```

大佬能加个QQ给个详细代码吗？SaveInstanceMessage这里面怎么写，对原生不太懂啊

**Comment by ma6566966** [comment]
> @gao520sun 请问下你 itent.setClass(ThirdPartMessageActivity.this, MainActivity.class); 这其中的MainActivity什么怎么写的？ 怎么做到跨package打开特定Activity, 然后顺利传值的呢？
> 
> 试了许久，一直不能成功跳转

大佬能加个QQ412804180给个详细代码吗？SaveInstanceMessage这里面怎么写，对原生不太懂啊
