### ISSUE TITLE
ios真机getdeviceid报错

### ISSUE THREAD

**Issue by ftb2010** [wonday/react-native-aliyun-push#30]
-[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]' was thrown while invoking getDeviceId on target AliyunPush with params (
    49
)

react-native-aliyun-push@1.0.10
好像原来使用1.0.9是好的，是不是ios sdk有什么问题

**Comment by wonday** [comment]
你这个会导致app崩溃吗？或者还是个警告？
我在真机及模拟器上都测试过1.0.10，没发现这个错误呀。
你测试的环境？ios版本， Xcode版本?
另外，  是1.0.9还是1.0.8？ 1.0.9有其他问题被我废弃掉了。
1.0.8->1.0.10主要就是更新sdk。

**Comment by hellobbq** [comment]
@ftb2010 我也是出错，你那边找到解决办法了吗

**Comment by ftb2010** [comment]
删掉应用，重启手机，xcode clean

**Comment by hellobbq** [comment]
@ftb2010 那模拟器正常吗,可劲的折腾s了
