### ISSUE TITLE
安卓有通知栏收不到通知，还有除了收到通知回调，有点击通知回调吗？

### ISSUE THREAD

**Issue by cq0702** [wonday/react-native-aliyun-push#35]
oppo手机，手机的通知打开了，收到通知后也能触发回调，AliyunPush.addListener(this.handleAliyunPushMessage);但是通知栏就是没有通知，不管app是杀死还是活跃状态，前台还是后台都不行。还有，进去看了下代码，是不是没有监听点击通知的回调方法啊？有的话是哪个呢。坐等作者告知，谢谢

**Comment by wonday** [comment]
通知栏没有，是不是没有设置通知栏图标？就是pushService.setNotificationSmallIcon(R.mipmap.ic_launcher_s);//设置通知栏小图标， 需要自行添加
ic_launcher_s这个图标有吗？

另外监听

- 当app处于活动时：
回调AliyunPush.addListener(this.handleAliyunPushMessage);

- 当app非活动时:
我一般推送时设置点击打开一个url的方式，然后做一下app的schema url,
就是类似于 weixin://host/xxx?abc,  可以自定义一些参数带过去，app里面用React-Native下面的Linking接收schema url调用， 然后处理。

app初始处代码例子如下：
```
        AliyunPush.addListener(this.handleAliyunPushMessage);
        Linking.addEventListener('url', (e)=>{this.handleOpenURL(e.url);});
        Linking.getInitialURL().then((url) => {
            if (url) {
                this.handleOpenURL(url)
            }
        }).catch((err) => {
          
        });
```

**Comment by wonday** [comment]
关于小图标，请参照#33

**Comment by wonday** [comment]
另外关于oppo手机， app死掉时候是否能够收到推送也是未知， 国内手机的推送都有自己的做法。
例如小米华为等，没研究过oppo的。

**Comment by cq0702** [comment]
嗯，好的，作者很用心，我先试试
