### ISSUE TITLE
IOS 企业证书打包IPA，启动闪退

### ISSUE THREAD

**Issue by Covenanter** [wonday/react-native-aliyun-push#36]
`*** Terminating app due to uncaught exception 'RCTFatalException: Exception '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]' was thrown while invoking getDeviceId on target AliyunPush with params (
    5
)
callstack: (
	0   CoreFoundation                      0x000000018396ada4 <redacted> + 252
	1   libobjc.A.dylib                     0x0000000182b245ec objc_exception_throw + 56
	2   CoreFoundation                      0x0000000183903750 _CFArgv + 0
	3   CoreFoundation                      0x0000000183836a18 <redacted> + 284
	4   CoreFoundation                      0x0000000183842c78 <redacted> + 52
	5   Bytter                              0x00000001029f9188 _ZN5folly6detail15str_to_integralIxEENS_8ExpectedIT_NS_14ConversionCodeEEEPNS_5RangeIPKcEE + 456504
	6   CoreFoundation                      0x0000000183972580 <redacted> + 144
	7   CoreFoundation                      0x0000000183851748 <redacted> + 284
	8   CoreFoundation                      0x0<…> `

使用版本号
"react-native-aliyun-push": "1.0.11",
"react-native": "0.54.2",

已经替换了最新包中的libs
手机删除APP，重启手机，xcode clean，打包签名生成IPA，通过iFunbox安装到手机上，启动APP后提示“APP想给您发送通知”的alert提示框，这个时候app已经闪退。
允许通过推送后，再次点击APP，未进入到任何一个页面，直接闪退！
多次点启动APP闪退后，大约闪退8次之后，app启动正常

debug模式下能够正常接收推送信息。

补充：
我注释掉 `AliyunPush.getDeviceId`方法体的内容，试了下是不会闪退，那是不是证明在回调方法中执行
`AliyunPushNative.getDeviceId`这个方法是有问题的？

**Comment by Covenanter** [comment]
已解决了
我的场景是：进入到APP的时候就调用获取deviceId的方法获取deviceId，然后根据deviceId做别的事情。
大致跟了下源代码，发现在初始化方法的时候会异步调用阿里的api获取deviceId。

分析：
app启动时获取deviceId，这个动作是异步的，由于在debug模式下打印日志之类的动作所花费的时间足够api生成deviceId，因此，在debug模式下是正常的。
在生成ipa也就是生成模式下，打印日志或调试之类的动作将被取消，所以api执行的时间并不足以获取deviceId，在调用获取deviceId的时候，objectc将一个空置赋值到一个数组中造成了异常，也就是最直接的闪退现象。

不知道我以上的分析对不对。
解决办法：
在获取deviceId的时候使用延迟获取

`
setTimeout(()=>{
    这里填写获取deviceId的方法
},2000)
`
就能得到deviceId

**Comment by wonday** [comment]
可能代码需要加一些保护
```
RCT_EXPORT_METHOD(getDeviceId:(RCTResponseSenderBlock)callback)
{
    NSString *deviceId = [CloudPushSDK getDeviceId];
    if (deviceId==Nil) deviceId = @""; // 加这一行看看？不会报错， 失败返回空串
    callback(@[deviceId]);
}
```
