### ISSUE TITLE
AliyunPush.getDeviceId 报错

### ISSUE THREAD

**Issue by hexiao-o** [wonday/react-native-aliyun-push#39]
ios过审时没通过，原来是ios在初次安装应用时，在未选允许发送退知权限时，调用AliyunPush.getDeviceId 会报错
AliyunPush.getDeviceId(deviceId => {
 console.log(`AliyunPush DeviceId: ${deviceId}`)
})

iphone7
react-native: 0.55.4
aliyun-push: 1.0.11

**Comment by wonday** [comment]
发布了v1.0.12, getDeviceId()接口变更为Promise模式, 可以增加取得失败的处理。
