### ISSUE TITLE
小米0条未读消息的通知

### ISSUE THREAD

**Issue by lzctbyong** [wonday/react-native-aliyun-push#4]
`
@Override
    public void onHostPause() {
        //小米特殊处理, 处于后台时更新角标， 否则会被系统清除，看不到
        if (MIUIUtils.isMIUI()) {
            Log.d(ReactConstants.TAG, "onHostPause:setBadgeNumber for xiaomi");
            //MIUIUtils.setBadgeNumber(this.mRAC, getCurrentActivity().getClass(), badgeNumber);
        }
    }`

   ` @Override
    public void onHostDestroy() {
        //小米特殊处理, 处于后台时更新角标， 否则会被系统清除，看不到
        if (MIUIUtils.isMIUI()) {
            Log.d(ReactConstants.TAG, "onHostDestroy:setBadgeNumber for xiaomi");
            //MIUIUtils.setBadgeNumber(this.mRAC, getCurrentActivity().getClass(), badgeNumber);
        }
    }`

你这段代码会让小米，一直显示一个“0条未读消息”的通知

**Comment by wonday** [comment]
好吧， 应该判断一下如果不是0条才设置，我修改一下。
