### ISSUE TITLE
安卓退出应用后收不到通知？

### ISSUE THREAD

**Issue by hellobbq** [wonday/react-native-aliyun-push#41]
打开应用的时候连续接收到，有没有办法？是我设置问题吗还是？

**Comment by wonday** [comment]
退出应用要接到通知，只有以下几种情况可以。
1. 苹果
2. 小米
3. 华为
4. 谷歌原生推送
4. 其他有用阿里云推送的app并且活着的

小米和华为都需要申请对应的账号，并在阿里云里面进行设置。具体设置请自行查找小米/华为及阿里云资料吧。

本来谷歌推送阿里云也是支持的，只是由于国内被墙，是用不了的。

**Comment by hellobbq** [comment]
非常感谢
