### ISSUE TITLE
安卓上通知栏不显示推送，app内可以收到

### ISSUE THREAD

**Issue by zlipeng** [wonday/react-native-aliyun-push#42]
在app内部推送通知和消息都能够通过监听获取到，但是通知栏没有反应。查看app的权限是有通知权限的，手机是nexus6p。
另外通知栏的小icon也都有设置。

但是，就是没有通知栏，请问有人遇到过这种情况吗？

**Comment by wonday** [comment]
app活着的时候，通知栏好像不显示的，直接通知到了app
app死掉的时候， 会有。但是nexus6p系列国内不支持。
具体请参见 #41
