### ISSUE TITLE
安卓build出错

### ISSUE THREAD

**Issue by zlipeng** [wonday/react-native-aliyun-push#47]
<img width="740" alt="2018-07-25 10 43 10" src="https://user-images.githubusercontent.com/9947224/43176767-d0cddcae-8ff7-11e8-9ecb-2a554da2d534.png">

仔细检查了配置没有发现错误，但是不知道为什么出现了这个错误

**Comment by wonday** [comment]
看不出什么， 是不是npm install不完整？
把node_modules删掉，重新npm install一下呢？

**Comment by zlipeng** [comment]
这段时间我采用手动方式，将阿里推送的sdk直接放到项目libs下，然后compile本地的jar等文件，封装的代码还是直接用作者的。

然后在demo中测试是没有什么问题，build可以成功。但是在项目中就会有Program type already present: com.ta.utdid2.a.a 等类似的错误。至今找不到是什么原因。头疼，一天就这么过去了。
