### ISSUE TITLE
使用最新版本，安卓无法接收到通知和消息

### ISSUE THREAD

**Issue by Covenanter** [wonday/react-native-aliyun-push#50]
使用版本是v1.0.13，安卓无法接收到通知和消息。

在前几个版本android是可以接收到消息的。
在android中的MainApplication中register打印日志，返回的是绑定成功
在RN中获取到deviceId，然后用得到的deviceId到阿里的控制台查看设备，设备是在线的。在RN的debug模式中，打印账号绑定参数是成功的。

在IOS上能够通过阿里控制台的推送接收到。
在android上，通过两台华为机器测试，无法收到消息和通知，不知道是什么原因造成的。

**Comment by wonday** [comment]
如果在杀掉app情况下想收到推送消息，
华为手机需要注册华为账号， 然后阿里端要填写华为的app信息。
由于手头上一直没有华为手机， 所以不知道华为是否能够推送成功。
有其他人测试过吗？

**Comment by Covenanter** [comment]
之前我在做安卓测试的时候，用的是华为手机，在没有杀死进程的情况下，是可以正常接收到消息推送的。稍后我弄个干净的工程在测试下安卓的推送

**Comment by wonday** [comment]
没有杀死情况下走的是阿里通道， 不配置华为app信息，应该可以收到的，
杀死的情况下就需要走华为自己的通道， 这个要配置华为app信息

**Comment by Covenanter** [comment]
新的工程测试可以收到消息，可能是我的项目有某些地方冲突吧！
