### ISSUE TITLE
提交苹果商店，返回crashlog

### ISSUE THREAD

**Issue by since66** [wonday/react-native-aliyun-push#51]
Thread 12 name:  Dispatch queue: com.facebook.react.AliyunPushQueue
Thread 12 Crashed:
0   libsystem_kernel.dylib        	0x0000000183ec12e0 0x183e9f000 + 140000
1   libsystem_pthread.dylib       	0x0000000184062288 0x18405f000 + 12936
2   libsystem_c.dylib             	0x0000000183e2fd0c 0x183dcd000 + 404748
3   libc++abi.dylib               	0x00000001835ca2c8 0x1835c9000 + 4808
4   libc++abi.dylib               	0x00000001835ca470 0x1835c9000 + 5232
5   libobjc.A.dylib               	0x00000001835f48d4 0x1835ec000 + 35028
6   dzcdriver                     	0x0000000100281e50 0x1000a4000 + 1957456
7   libc++abi.dylib               	0x00000001835e437c 0x1835c9000 + 111484
8   libc++abi.dylib               	0x00000001835e3ccc 0x1835c9000 + 109772
9   libobjc.A.dylib               	0x00000001835f4720 0x1835ec000 + 34592
10  dzcdriver                     	0x0000000100120f60 0x1000a4000 + 511840
11  dzcdriver                     	0x0000000100176650 0x1000a4000 + 861776
12  dzcdriver                     	0x00000001001761c8 0x1000a4000 + 860616
13  libdispatch.dylib             	0x0000000183d2caa0 0x183d2b000 + 6816
14  libdispatch.dylib             	0x0000000183d2ca60 0x183d2b000 + 6752
15  libdispatch.dylib             	0x0000000183d369b4 0x183d2b000 + 47540
16  libdispatch.dylib             	0x0000000183d372fc 0x183d2b000 + 49916
17  libdispatch.dylib             	0x0000000183d37cc8 0x183d2b000 + 52424
18  libdispatch.dylib             	0x0000000183d40098 0x183d2b000 + 86168
19  libsystem_pthread.dylib       	0x000000018405fe70 0x18405f000 + 3696
20  libsystem_pthread.dylib       	0x000000018405fb08 0x18405f000 + 2824
请问这是什么问题？

**Comment by wonday** [comment]
最新版本吗？旧版本可能回发生类似的问题，最新版本应该避免掉了。

**Comment by since66** [comment]
1.0.11，我升级1.0.13试试

**Comment by wonday** [comment]
对的， 从1.0.12才开始修正的
