### ISSUE TITLE
Found an unexpected Mach-O header code: 0x72613c21

### ISSUE THREAD

**Issue by navy774989** [wonday/react-native-aliyun-push#52]
打包完後 想要上傳卻跳出 這個錯誤訊息
<img width="643" alt="screen shot 2018-08-28 at 7 34 51 pm" src="https://user-images.githubusercontent.com/24507808/44720461-8208e600-aaf9-11e8-956d-4f7b0f11dcab.png">
以下是我framework 放置
<img width="251" alt="screen shot 2018-08-28 at 7 35 34 pm" src="https://user-images.githubusercontent.com/24507808/44720559-c72d1800-aaf9-11e8-8b53-01d16786e489.png">
<img width="690" alt="screen shot 2018-08-28 at 7 36 08 pm" src="https://user-images.githubusercontent.com/24507808/44720560-c7c5ae80-aaf9-11e8-8d2c-2d319754155a.png">

**Comment by wonday** [comment]
看上去没什么问题，和我自己的程序差不多，我不知道原因了，你搞定了吗？其他人有知道的吗？

**Comment by navy774989** [comment]
我搞定了 是UTDID 在被npm安裝時有機會裝到壞掉的 我重裝幾次後就可以正常使用了

**Comment by MttNajafi** [comment]
@navy774989 @wonday  I have the same problem but I can not find the problem. can you help me?
