### ISSUE TITLE
Android 8能接受到通知，但无法弹出窗口

### ISSUE THREAD

**Issue by Covenanter** [wonday/react-native-aliyun-push#53]
在Android 6上测试正常。。
Android 8 无法弹出窗口，查看了下阿里的文档
[https://help.aliyun.com/knowledge_detail/67398.html](url)

能否通过RN配置NotificationChannel？

**Comment by Covenanter** [comment]
目前自己已经在MainActivity中新增阿里文档中的代码即可

**Comment by Adar-Li** [comment]
@Covenanter 我也遇到了相同的问题 并且配置了MainApplication新增的代码 但是还是收不到，能帮忙看下吗？

**Comment by wublack** [comment]
@Adar-Li 我也遇到了，有解决吗？能分享一下怎么解决的吗

**Comment by Adar-Li** [comment]
@wublack Android8.0推送需要在服务端加一个参数 具体你看下文档就可以了
