### ISSUE TITLE
ipad ios9.3 收到通知后闪退

### ISSUE THREAD

**Issue by ftb2010** [wonday/react-native-aliyun-push#54]
ipad ios9.3 前台收到通知后闪退，最小化收到通知后点击通知栏闪退

**Comment by ftb2010** [comment]
发布到app store 提示ipad ios 11.4也崩溃

**Comment by chengxuwang** [comment]
@ftb2010 你好你解决了吗，我这边也有着同样的那问题

**Comment by ftb2010** [comment]
> @ftb2010 你好你解决了吗，我这边也有着同样的那问题

没有，需要作者解决

**Comment by wonday** [comment]
我在iPad 11.4.1上测试是OK的

**Comment by ftb2010** [comment]
[attachment-836958624968818736crashlog-AC711482-6B8C-437E-9DB6-98F3EBFBABF9.txt](https://github.com/wonday/react-native-aliyun-push/files/2396149/attachment-836958624968818736crashlog-AC711482-6B8C-437E-9DB6-98F3EBFBABF9.txt)
这个是崩溃日志，用最新版的试了，ipad收到通知后点击通知栏闪退

**Comment by wonday** [comment]
debug状态下崩溃吗？是原生代码里还是js 里面能抓到吗？以前是弹出权限提醒如果用户不允许再启动会崩溃

**Comment by ftb2010** [comment]
debug 自动跳到这里
#import <UIKit/UIKit.h>

#import "AppDelegate.h"

int main(int argc, char * argv[]) {
@autoreleasepool {
return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));//debug时这里报Thread 1: signal SIGABRT
}
}

**Comment by chengxuwang** [comment]
@wonday  不是debug状态下，放到蒲公英给用户的内测的，他的ios版本是9.3，怀疑是ios版本过低处理打开通知出现的问题

**Comment by wonday** [comment]
这里看不出来什么，是整个程序入口处。模拟器或者iPad上显示了什么信息？断点或者注释一些信息逐步找到发生问题的地方才好判断，目前信息我无法判断问题在哪里

**Comment by wonday** [comment]
9.3没环境，上面也说了11.4也同样有问题，是吗？

**Comment by ftb2010** [comment]
是的

**Comment by ftb2010** [comment]
我的页面传的有额外参数，用于跳转，有可能是跳转出错了

**Comment by wuzhijiangithub** [comment]
我的ipad mini ios9.3.2存在同样的问题

**Comment by haipengz** [comment]
经过iOS同事协助，使用XCode调试，
发现问题所在：
[ios/RCTAliyunPush/AliyunPushManager.m#L579](https://github.com/wonday/react-native-aliyun-push/blob/master/ios/RCTAliyunPush/AliyunPushManager.m#L579)
这行代码：
```ObjectiveC
notificationDict[@"date"] = [NSDate init];
```
应该改为：
```ObjectiveC
notificationDict[@"date"] = [[NSDate alloc] init];
```

iOS同事的吐槽：这谁写的代码？不分配内存空间就初始化对象了？！如果是阿里的人写出这样的代码就该炒了。

囧

**Comment by haipengz** [comment]
iOS低版本容错性比较差。

**Comment by haipengz** [comment]
已提交PR #72
@wonday

**Comment by wonday** [comment]
已合并并发布为 v1.0.16
