### ISSUE TITLE
Main Thread Checker: UI API called on a background thread

### ISSUE THREAD

**Issue by xinfang** [wonday/react-native-aliyun-push#55]
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 2630, TID: 984915, Thread name: CCP Socket Thead, Queue name: com.apple.root.default-qos.overcommit, QoS: 21
Backtrace:
4   myApp                              0x000000010285c704 -[AliyunPushManager sendEventToJs:] + 996
5   myApp                              0x000000010285c2d4 -[AliyunPushManager onMessageReceived:] + 1108
6   CoreFoundation                      0x0000000183a58c3c <redacted> + 20
7   CoreFoundation                      0x0000000183a581b8 <redacted> + 428
8   CoreFoundation                      0x0000000183a57f14 <redacted> + 216
9   CoreFoundation                      0x0000000183ad584c <redacted> + 1408
10  CoreFoundation                      0x000000018398ef38 _CFXNotificationPost + 384
11  Foundation                          0x00000001843ffbbc <redacted> + 68
12  myApp                              0x00000001027a9770 -[MPCCPProtocolHandler handlePushMsg:] + 1184
13  myApp                              0x00000001027b01d0 -[MPASConnectTask decoderHandleMessage:] + 916
14  myApp                              0x00000001027c02d8 -[CCPDecoder stream:handleEvent:] + 2508
15  CoreFoundation                      0x00000001839ffb34 <redacted> + 212
16  CoreFoundation                      0x00000001839ffa40 <redacted> + 460
17  CoreFoundation                      0x0000000183a6f404 <redacted> + 24
18  CoreFoundation                      0x0000000183a6ec2c <redacted> + 276
19  CoreFoundation                      0x0000000183a6c79c <redacted> + 1204
20  CoreFoundation                      0x000000018398cda8 CFRunLoopRunSpecific + 552
21  Foundation                          0x0000000184401674 <redacted> + 304
22  Foundation                          0x00000001844761a8 <redacted> + 88
23  myApp                              0x00000001027afb14 -[MPASConnectTask networkRequestThreadEntryPoint:] + 216
24  Foundation                          0x0000000184511efc <redacted> + 1040
25  libsystem_pthread.dylib             0x00000001836ed220 <redacted> + 272
26  libsystem_pthread.dylib             0x00000001836ed110 <redacted> + 0
27  libsystem_pthread.dylib             0x00000001836ebb10 thread_start + 4

```AliyunPushManager.m
    AliyunPushManager* __weak weakSelf = self;
    dispatch_async(dispatch_get_main_queue(), ^{
        //修正app退出后，点击通知会闪退bug
        if([UIApplication sharedApplication].applicationState == UIApplicationStateActive
           ||[UIApplication sharedApplication].applicationState == UIApplicationStateInactive) {
            [weakSelf sendEventWithName:@"aliyunPushReceived" body:notification];
        }
    });
```

**Comment by wonday** [comment]
@xinfang 
谢谢，我将你的代码添加到了v1.0.4
