### ISSUE TITLE
ios 报错

### ISSUE THREAD

**Issue by GuoJiKaiHehe** [wonday/react-native-aliyun-push#58]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AliyunPushManager", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by wonday** [comment]
不知道是哪里错误，我提交了一个sample, 可以作为参考。
