### ISSUE TITLE
有能运行成功的demo吗？ 能发我一份吗？

### ISSUE THREAD

**Issue by GuoJiKaiHehe** [wonday/react-native-aliyun-push#59]
邮箱，970228812@qq.com ， 或者，给给链接我下载一下， 现在我ios集成不成功。 好尴尬啊，不知道哪里错了

**Comment by wonday** [comment]
我提交了一个sample, 是从我的一个程序精简下来的。你可以参考一下其中的代码和设置。
注意替换相关阿里云账号，另外ios版simulator是无法实际接收推送的，必须要真机。
