### ISSUE TITLE
绑定账号失败，bindAccount error  {"framesToPop":1,"code":"20101"}

### ISSUE THREAD

**Issue by KingAmo** [wonday/react-native-aliyun-push#60]
AliyunPush.bindAccount('13003672432')
      .then((data) => {
        console.log('bindAccount success');
        console.log(JSON.stringify(data));
      })
      .catch((error) => {
        console.log('bindAccount error');
        console.log(JSON.stringify(error));
      });
查了一下官网，20101解释是‘参数非法，详见具体错误信息’
但是我甚至把手机号码固定死了，还是报这个错{"framesToPop":1,"code":"20101"}

   版本号： "react-native-aliyun-push": "^1.0.11",
Android端

**Comment by wonday** [comment]
getDeviceId()可以取得成功吗？是不是没有初始化好？
这里也没什么特殊的，直接包装了阿里云的接口。

**Comment by wonday** [comment]
我提交了一个sample, 可以作为参考。

**Comment by jsshizhan** [comment]
我也遇到这个问题了，不知道怎么回事

**Comment by jsshizhan** [comment]
packagename 配置错了  — —！

**Comment by limitLiu** [comment]
把包名 配正确 然后重启模拟器再测试 基本上能正常
