### ISSUE TITLE
app杀死后，监听未被注册的问题

### ISSUE THREAD

**Issue by zlipeng** [wonday/react-native-aliyun-push#63]
大概是这样的一种情况，app处于杀死状态的时候弹出了通知，这个时候点击通知会打开app，开始加载我们写的RN的逻辑。

这个时候会存在 `Sending aliyunPushReceived with no listenners registered`的warning。

同时我们的监听也没有收到通知消息，只是启动了app进入了默认的页面。

我的判断是原生程序将通知发送给js的时候RN还没有启动起来，各个页面还都未装载，所以写在RN内的监听也就未被注册。

所以如果想根据通知内容进行不同页面的跳转，而且又能保证在杀死时也能准确无误，要怎么处理呢？

有没有遇到过相似问题的朋友？
@wonday

**Comment by wonday** [comment]
- 当app处于活动时：
回调AliyunPush.addListener(this.handleAliyunPushMessage);

- 当app非活动时:
我一般推送时设置点击打开一个url的方式，然后做一下app的schema url,
就是类似于 weixin://host/xxx?abc, 可以自定义一些参数带过去，app里面用React-Native下面的Linking接收schema url调用， 然后处理。
app初始处代码例子如下：
```
        AliyunPush.addListener(this.handleAliyunPushMessage);
        Linking.addEventListener('url', (e)=>{this.handleOpenURL(e.url);});
        Linking.getInitialURL().then((url) => {
            if (url) {
                this.handleOpenURL(url)
            }
        }).catch((err) => {
          
        });
```
