### ISSUE TITLE
android可以获取到 deviceId，但是手机不提示声音。

### ISSUE THREAD

**Issue by Adar-Li** [wonday/react-native-aliyun-push#66]
阿里云版本：v1.0.15
RN版本：0.57.1
描述：现在是监听推送信息是可以收到的，但是手机没有任何提示声音和弹框
手机型号：android 华为

**Comment by chengxuwang** [comment]
@Adar-Li  你好，请问你解决了吗，我也是0.57版本，同样是有消息没通知，而我在之前其他项目是的rn是0.51版本并没有问题

**Comment by Adar-Li** [comment]
@chengxuwang 这个和RN 版本没关系，你的手机是 android8.0系统吗

**Comment by chengxuwang** [comment]
@Adar-Li  你好，这个问题刚刚解决了，看了作者的问题什么都没问题，问题在于服务端，服务端要配置通知渠道的ID

**Comment by Adar-Li** [comment]
@chengxuwang 好的 解决就好！
