### ISSUE TITLE
小米手机点击通知多次启动app问题

### ISSUE THREAD

**Issue by zlipeng** [wonday/react-native-aliyun-push#67]
手机： 小米
系统：MIUI9和MIUI10下

app在前台时，点击通知，会重新打开一个该app，这时候点击手机返回键会返回到之前app，然后会闪退。
或者点击通知，会启动一个白屏

已经测试过发通知时不使用辅助通道推送仍然会是上面的情况。

提阿里工单，回应说可能是辅助通道配置问题。

有没有遇到过这样问题的朋友，是怎么解决的

**Comment by zlipeng** [comment]
是由MIUIUtils自定义MIUI角标引起的，注释掉就没事了

**Comment by wonday** [comment]
>是由MIUIUtils自定义MIUI角标引起的，注释掉就没事了
注释的是你的代码还是我的代码？
