### ISSUE TITLE
在ios上面报编译错误

### ISSUE THREAD

**Issue by swj735245824** [wonday/react-native-aliyun-push#70]
我按照提示上面做的，但是不知道怎么回事，ios报这个编译错误
![1547629711619](https://user-images.githubusercontent.com/12065843/51238219-62dbf980-19b1-11e9-8189-c3f3e4a205c9.jpg)

**Comment by swj735245824** [comment]
<img width="530" alt="wx20190116-171109 2x" src="https://user-images.githubusercontent.com/12065843/51238400-d1b95280-19b1-11e9-8ba5-b23d979f00ea.png">

**Comment by wonday** [comment]
你用的是我包里面的阿里云SDK还是阿里网站下载的？
网站上下载的打包格式有问题。
仔细核对一下下面的操作说明
```
拖拽node_modules/react-native-aliyun-push/ios/libs下列目录到xcode工程的frameworks目录下，将copy items if needed打勾。 注意：从阿里云下载的SDK中UTDID.framework有问题，编译会报错，请使用react-native-aliyun-push中内置的版本。

AlicloudUtils.framework
CloudPushSDK.framework
UTDID.framework
UTMini.framework
```

**Comment by swj735245824** [comment]
嗯，那个步骤没问题，第一步我怎么操作？
![image](https://user-images.githubusercontent.com/12065843/51241778-83a84d00-19b9-11e9-8c67-3e173db938fd.png)

**Comment by wonday** [comment]
就是看
如果你已经执行过```react-native link react-native-aliyun-push```, 那个应该有了，

**Comment by swj735245824** [comment]
这下我可是一步一步来的啊，会不会是Xcode升级的问题呢？
![image](https://user-images.githubusercontent.com/12065843/51244842-0da7e400-19c1-11e9-8d43-101822a9c881.png)

**Comment by wonday** [comment]
不会，我也用最新的Xcode，没问题。
你看看我的sample比较一下

**Comment by wonday** [comment]
不知你是否搞定了， 我修改了一下配置说明，你第二步加一下再试试。

1. 执行```react-native link react-native-aliyun-push```或手工添加node_modules/react-native-aliyun-push/ios/RCTAliyunPush.xcodeproj到xcode项目工程

2. 点击项目根节点，在targets app的```Build Settings```中找到```Framework search path```, 添加```$(PROJECT_DIR)/../node_modules/react-native-aliyun-push/ios/libs```

3. 添加阿里云移动推送SDK

拖拽node_modules/react-native-aliyun-push/ios/libs下列目录到xcode工程的```frameworks```目录下，选择```create folder references```。

- AlicloudUtils.framework
- CloudPushSDK.framework
- UTDID.framework
- UTMini.framework

4. 点击项目根节点，在targets app的BuildPhase的Link Binary With Libraries中添加公共包依赖

- libz.tbd
- libresolv.tbd
- libsqlite3.tbd
- CoreTelephony.framework
- SystemConfiguration.framework
- UserNotifications.framework
