### ISSUE TITLE
希望能添加一个能移除所有监听的功能

### ISSUE THREAD

**Issue by weifengzz** [wonday/react-native-aliyun-push#75]
希望能添加一个能移除所有监听的功能，如：removeAllListeners()，可以防止某些特殊情况下，多次添加监听或没正确移除监听，导致监听多次的问题。

**Comment by wonday** [comment]
我在master上添加了， 你可以先试试，没问题我稍后发布一下。

**Comment by weifengzz** [comment]
好的，非常感谢，看了您添加的代码，我认为没有问题。我现在由于没法进行测试，等我测试好了，再给您回复。

**Comment by wonday** [comment]
已发布为v1.0.17
